plugins {
    id 'com.android.application'
}

android {
    namespace 'org.trust.forensicshell'
    compileSdk 34

    defaultConfig {
        applicationId "org.trust.forensicshell"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    sourceSets {
        main {
            assets.srcDirs = ['src/main/assets']
        }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.biometric:biometric:1.2.0-alpha05'
}
